### ISSUE TITLE
Redesign JsonDataSerializer

### ISSUE THREAD

**Issue by dualbios** [dualbios/FileBaseContext#12]
Redesign JsonDataSerializer to use typed date instead of serialised 
AR:
stored like 
 {
    "Value": "5"
   "IsOpened" : "True"
  },

ER
must be stored like 
 {
    "Value":  5,
   "IsOpened" : true
  },

**Comment by daveidmx** [comment]
Should be addressed by #17

**Comment by dualbios** [comment]
closed by https://github.com/dualbios/FileBaseContext/pull/17
