### ISSUE TITLE
csv serializer should put proper line-end character

### ISSUE THREAD

**Issue by GreatNovaDragon** [dualbios/FileBaseContext#24]
Currently, the csv serializer puts a newline for a lineend, which doesnt properly work, when a field itself is a multi-line text. Which would resolve in malformed parsing like this

![grafik](https://github.com/dualbios/FileBaseContext/assets/14358593/36131096-0709-4657-ae54-0d2b61c74232)

**Comment by GreatNovaDragon** [comment]
Actually, the error with this parsing may lie somewhere else, but a new line does NOT equal a new row anyways

**Comment by dualbios** [comment]
fixed in 4.0.1 by https://github.com/dualbios/FileBaseContext/pull/26
