### ISSUE TITLE
Issue with ASP.NET Core Identity

### ISSUE THREAD

**Issue by mguinness** [dualbios/FileBaseContext#3]
Firstly, thanks for creating this provider.  I'm hoping to use this in a new open source project that is an admin tool for Identity.

However, I've hit an issue when trying to save to the `AspNetUserClaims` table using the Identity API and get the following exception:

`The property 'IdentityUserClaim<string>.Id' does not have a value set and no value generator is available for properties of type 'int'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'int' in 'OnModelCreating'.`

I've tried this with the SQLite provider and there is no exception.  The sample project [WebApplication2.zip](https://github.com/dualbios/FileBaseContext/files/12924294/WebApplication2.zip) will allow you to repro if you have time.  To test you would register an account and then go to the Privacy link to simulate adding a claim for the user.

**Comment by mguinness** [comment]
OK, there is no issue with the provider.  I was confused by the PK being an `int` but that appears to be by design as per [Microsoft.AspNetCore.Identity.IdentityUserClaim<TKey> enforce Id as integer](https://github.com/dotnet/aspnetcore/issues/21945).

To workaround I had to create a `ValueGenerator` which generates a random number (OK for development purposes).

```C#
internal class DummyIdValueGenerator : ValueGenerator<int>
{
    public override bool GeneratesTemporaryValues => false;

    public override int Next(EntityEntry entry)
    {
        return new Random().Next(1, Int32.MaxValue);
    }
}
```

Then in the `ApplicationDbContext` I had to use the following in `OnModelCreating` to use it for the PK.

```C#
builder.Entity<IdentityUserClaim<string>>(entity =>
{
    entity.Property(p => p.Id).HasValueGenerator<DummyIdValueGenerator>();
});
```

**Comment by dualbios** [comment]
Hi @mguinness , thanks a lot for using the provider and found the workaround.

**Comment by chaospixel** [comment]
It would be super useful to have the provider use a generator like that for properties attributed with:         [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
