### ISSUE TITLE
Mapping a long string   ?

### ISSUE THREAD

**Issue by ignatandrei** [dualbios/FileBaseContext#30]
I do like the library . However, one question : If I want to map a long string,  do you have a suggestion ?

**Comment by dualbios** [comment]
Hi @ignatandrei , thanks.
Could you please give an example of the data structure and data that you want to map?

**Comment by ignatandrei** [comment]
```json
  {
    "Id": 2,
    "Stage":"done",
    "Title": "NullObject",
    "Description":"Instead of returning null , use an object which implements the expected interface, but whose method body is empty.",
    "LinkWikipedia":"https://en.wikipedia.org/wiki/Null_object_pattern",
    "DemoFileCsproj":"NullObject.csproj",
    "ClassNames":"EmptyFolder,NullLogger",
    "Homework":"When retrieving data( e.g. a Person with ID =-1 ) from a database , return a NullObject instead of null. How you will verify that the object is a NullObject?",
    "Tags":"behavioral,design pattern"    

  }
```

I do with description and Homework to be as an array ( each item of the array could be a line )

**Comment by ignatandrei** [comment]
Any suggestions?

**Comment by dualbios** [comment]
Hi, thanks for example. Working on it.

**Comment by dualbios** [comment]
Hi @ignatandrei as I understand you want to set the type of 'Homework' to 'string[]', like that
```
{
                    "Id": 2,
                    "Stage": "done",
                    "Title": "NullObject",
                    "Description": "Instead of returning null, use an object which implements the expected interface, but whose method body is empty.",
                    "LinkWikipedia": "https://en.wikipedia.org/wiki/Null_object_pattern",
                    "DemoFileCsproj": "NullObject.csproj",
                    "ClassNames": "EmptyFolder,NullLogger",
                    "Homework": [
                        "When retrieving data (e.g. a Person with ID =-1) from a database, return a NullObject instead of null.",
                        "How will you verify that the object is a NullObject?"
                    ],
                    "Tags": "behavioral,design pattern"
                }
```

Unfortunately, the EF does not support an array and throws an exception 'The property 'DesignPattern.Homework' could not be mapped because it is of type 'string[]', which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating' when trying it.

If you have comments on it you can try to play with it in the 'try-to-support-string-array' branch and let me know.

**Comment by dualbios** [comment]
In case when you need to have 'Homework' property as a 'string[]' you can use a converter for that property.
https://learn.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations

**Comment by ignatandrei** [comment]
How this value converter could be coded, since, you said previously, "could not be mapped because it is of type 'string[]', which is not a supported primitive type or a valid entity type" ?

**Comment by ignatandrei** [comment]
The problem is " When saving the string[] to the database, it will be serialized into a single comma-separated string"

This is something that is difficult in JSON . So instead of having

{
"description":"One long sentence . And another long sentence. And another"
} 
we can have , in your implementation
{
"description":[
"One long sentence.",
" And another long sentence. ",
"And another"
]
} 

as an easy to read array of sentences. But will be somehow serialized back as string, not as string[]

**Comment by dualbios** [comment]
Sorry, I have missed the core of your idea. Could you please describe the data schema of the database and EF? 
In other words, what is a template of data stored in a database, and what is a template of data in EntityFramework?

**Comment by mguinness** [comment]
It's not clear to me why you can't simply use newline characters?  Not sure why a string array is necessary.  As already requested, you will have to provide some more context.

```C#
using System;
using System.IO;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using kDg.FileBaseContext.Extensions;
					
public class Program
{
    public static void Main()
    {
        var db = new Context();		
        db.Lessons.Add(new Lesson {
            Id = 2,
            Stage = "done",
            Title = "NullObject",
            Description = "Instead of returning null , use an object which implements the expected interface, but whose method body is empty.",
            LinkWikipedia = "https://en.wikipedia.org/wiki/Null_object_pattern",
            DemoFileCsproj = "NullObject.csproj",
            ClassNames = "EmptyFolder,NullLogger",
            Homework = "When retrieving data( e.g. a Person with ID =-1 ) from a database , return a NullObject instead of null.\nHow you will verify that the object is a NullObject?",
            Tags = "behavioral,design pattern"
        });
        db.SaveChanges();
        
        Console.WriteLine(File.ReadAllText("my_local_db/Lesson.json"));
        
        var entry = db.Lessons.FirstOrDefault();
        
        Console.WriteLine("{0}: {1}", entry.Id, entry.Homework);
    }
}

public class Lesson
{
    public int Id { get; set; }
    public string Stage { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string LinkWikipedia { get; set; }
    public string DemoFileCsproj { get; set; }
    public string ClassNames { get; set; }
    public string Homework { get; set; }
    public string Tags { get; set; }
}

public class Context : DbContext
{
    public DbSet<Lesson> Lessons { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseFileBaseContextDatabase("my_local_db");
    }
}
```
